Fixed version checking
VRK-YTI/yti-ui pull request #644
Opened 2023-12-15 04:23 UTC by topirissanen-atoz

2023-12-15 08:48 UTC, tomiviljanen requested changes

2023-12-15 08:48 UTC, tomiviljanen commented on datamodel-ui/src/modules/model/index.tsx
> +    // setVersion(getSlugAsString(router.query.ver));
commented code can be removed

2023-12-18 07:27 UTC, kkyttala approved these changes

2023-12-19 09:58 UTC, tomiviljanen approved these changes

2023-12-19 10:02 UTC, merged